{
 "title": "TCHK-MD Team",
 "description": "Created by Lenny",
 "tags": [
  "alerts",
  "TCHK",
  "Prometheus"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Gateway Interface Status",
   "type": "table",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "gateway_interface_status{group=\"tchk\"}"
    }
   ]
  },
  { "title": "Alert Notification Services", "type": "alertlist", "gridPos": { "h": 4, "w": 9, "x": 15, "y": 0 } },
  { "title": "TCHK by Lenny", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Services Subscribers on GW",
   "type": "singlestat",
   "description": "The number of subscribers (e.g. Proxy, Feed, GissingSub...) currently connected.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "admin_subscribers{job=\"hk-tcgateway\"}"
    },
    {}
   ]
  },
  {
   "title": "gateway_errors",
   "type": "singlestat",
   "description": "A counter for how many times the gateway service has reported an error to all services",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(gateway_interface_gateway_notification_total{type=\"error\"})"
    }
   ]
  },
  {
   "title": "TC services",
   "type": "graph",
   "description": "*akka.actor.processing-time (Histogram): Tracks how long did it take for the actor to process every message",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(akka_actor_processing_time_seconds_sum{job=\"hk-tcproxy-tchk1\"}[5m]))",
     "legendFormat": "hk-tcproxy-tchk1"
    },
    {
     "expr": "sum(rate(akka_actor_processing_time_seconds_sum{job=\"hk-tcproxy-tchk2\"}[5m]))",
     "legendFormat": "hk-tcproxy-tchk2"
    },
    {
     "expr": "sum(rate(akka_actor_processing_time_seconds_sumt{job=\"hk-tcgateway\"}[5m]))",
     "legendFormat": "hk-tcgateway"
    },
    {
     "expr": "sum(rate(akka_actor_processing_time_seconds_sum{job=\"hk-tchistory\"}[5m]))",
     "legendFormat": "hk-tchistor"
    },
    {
     "expr": "sum(rate(akka_actor_processing_time_seconds_sum{job=\"hk-treactor\"}[5m]))",
     "legendFormat": "hk-treactor"
    },
    {
     "expr": "sum(rate(akka_actor_processing_time_seconds_sum{job=\"hk-tcproxy-tchk8\"}[5m]))",
     "legendFormat": "hk-tcproxy-tchk8"
    },
    {
     "expr": "sum(rate(akka_actor_processing_time_seconds_sum{job=\"hk-tcproxy-tchk10\"}[5m]))",
     "legendFormat": "hk-tcproxy-tchk10"
    }
   ]
  },
  {
   "title": "TCHK1 pub-request",
   "type": "singlestat",
   "description": "The number of PubRequests from Spreadsheets",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(central_incoming_requests_total{group=\"tchk\",instance=\"172.29.2.45:9095\",job=\"hk-tcproxy-tchk1\",type=\"client-pub-request\"}[5m])"
    }
   ]
  },
  {
   "title": "TCHK2 pub-request",
   "type": "singlestat",
   "description": "The number of PubRequests from Spreadsheets",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "irate(central_incoming_requests_total{group=\"tchk\",job=\"hhk-tcproxy-tchk8\",type=\"client-pub-request\"}[5m])>0"
    },
    {}
   ]
  },
  {
   "title": "Gateway Heartbeats count",
   "type": "singlestat",
   "description": "The count of heartbeats received from any service",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(gateway_service_heartbeat_received_total_total{job=\"hk-tcgateway\"}[5m])>0"
    }
   ]
  },
  {
   "title": "Current Connection TCHK1",
   "type": "singlestat",
   "description": "S/S connection to TC",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "central_current_sessions{job=\"hk-tcproxy-tchk1\"}"
    }
   ]
  },
  {
   "title": "Current Connection TCHK2",
   "type": "singlestat",
   "description": "S/S connection to TC",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "central_current_sessions{job=\"hk-tcproxy-tchk2\"}"
    }
   ]
  },
  {
   "title": "Current Connection  HKGMDBB08",
   "type": "singlestat",
   "description": "S/S connection to TC",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "central_current_sessions{job=\"hk-tcproxy-tchk8\"}"
    }
   ]
  },
  {
   "title": "Current Connection HKGMDBB010",
   "type": "singlestat",
   "description": "S/S connection to TC",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "central_current_sessions{job=\"hk-tcproxy-tchk10\"}"
    }
   ]
  },
  {
   "title": "Tracer - Tcgissingpubxdf",
   "type": "singlestat",
   "description": "0 = off, 1 = ok, 2 = error",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "tracer_state{job=\"hk-tcgissingpubxdf\",instance=\"172.29.2.55:9084\"}"
    },
    {}
   ]
  },
  {
   "title": "Tracer - tcgissingpub",
   "type": "singlestat",
   "description": "0 = off, 1 = ok, 2 = error",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "tracer_state{job=\"hk-tcgissingpub\",instance=\"172.29.2.58:9092\"}"
    }
   ]
  },
  {
   "title": "Tracer - Tcgateway",
   "type": "singlestat",
   "description": "0 = off, 1 = ok, 2 = error",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 17 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "tracer_state{job=\"hk-tcgateway\",instance=\"172.29.2.53:9096\"}"
    }
   ]
  },
  {
   "title": "TC proxy",
   "type": "graph",
   "description": "The number of GatewayDataUpdates received from the Gateway. Each GatewayDataUpdate has a number of DataKey updates inside",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gateway_interface_gateway_data_updates_total{job=\"hk-tcproxy-tchk1\"}[5m])>0",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "rate(gateway_interface_gateway_data_updates_total{job=\"hk-tcproxy-tchk2\"}[5m])>0",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "rate(gateway_interface_gateway_data_updates_total{job=\"hk-tcproxy-tchk8\"}[5m])>0",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "rate(gateway_interface_gateway_data_updates_total{job=\"hk-tcproxy-tchk10\"}[5m])>0",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "HK Proxy Connection",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Proxy Connection" }
   ],
   "targets": [
    {
     "expr": "central_current_sessions{job=\"hk-tcproxy-tchk1\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "central_current_sessions{job=\"hk-tcproxy-tchk2\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "central_current_sessions{job=\"hk-tcproxy-tchk10\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "central_current_sessions{job=\"hk-tcproxy-tchk8\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "TC-Reactor",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(akka_system_processed_messages_total{tracked=\"true\",job=\"hk-treactor\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "TC-bloombergsub, TC-Gissingsub",
   "type": "graph",
   "description": "data updates we are passing to the throttle directly from Gissing",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(pre_throttle_accepted_total{instance=\"172.29.2.55:9094\"}[5m])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "rate(pre_throttle_accepted_total{instance=\"172.29.2.58:9091\"}[5m])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "datakeys_rejected_total{instance=\"172.29.2.55:9094\"}",
     "legendFormat": "Datakeys Rejected {{job}}"
    },
    {
     "expr": "datakeys_rejected_total{instance=\"172.29.2.58:9091\"}",
     "legendFormat": "Datakeys Rejected {{job}}"
    }
   ]
  },
  {
   "title": "Bloombergpub",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(bloomberg_publish_page_total{group=\"tchk\"}[5m])",
     "legendFormat": "{{job}} (Record)"
    },
    {
     "expr": "increase(bloomberg_publish_record_total{group=\"tchk\"}[5m])",
     "legendFormat": "{{job}} (page)"
    }
   ]
  },
  {
   "title": "TC-gissingpub",
   "type": "graph",
   "description": "This graph represent data updates we are passing to the throttle directly from Gissing",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(gissing_publish_duration_seconds_sum{job=\"hk-tcgissingpubxdf\"}[5m])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "rate(gissing_publish_duration_seconds_sum{job=\"hk-tcgissingpub\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "TC-History",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(akka_system_processed_messages_total{tracked=\"true\",job=\"hk-tchistory\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "TCHK Gateway services",
   "type": "graph",
   "description": "*akka.actor.processing-time (Histogram): Tracks how long did it take for the actor to process every message",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(akka_actor_processing_time_seconds_bucket{job=\"hk-tcgateway\"}[5m]))",
     "legendFormat": "TCGATEWAY PROCESSING"
    }
   ]
  },
  {
   "title": "Replicator",
   "type": "graph",
   "description": "akka_system_active_actors_count",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "akka_system_active_actors_count{job=\"hk-tcreplicatorJP\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "akka_system_active_actors_count{job=\"hk-tcreplicatorSG\"}",
     "legendFormat": "{{job}}"
    },
    {}
   ]
  },
  {
   "title": "TC-Feed",
   "type": "graph",
   "description": "This Graph represent the time series to compute which data updates need to go to which clients",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(calc_time_seconds_sum{job=\"hk-tcfeed\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "TC-History-File Writer",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(akka_actor_processing_time_seconds_count{job=\"hk-tchistory\",dispatcher=\"akka.actor.default-dispatcher\"}[5m]) >0",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Gateway Mailbox",
   "type": "graph",
   "description": "*akka.actor.time-in-mailbox (Histogram): Tracks the time measured from the moment a message was enqueued into an actor’s mailbox until the moment it was dequeued for processing.\n*akka.actor.processing-time (Histogram): Tracks how long did it take for the actor to process every message.\n*akka.actor.mailbox-size (Range Sampler): Tracks the size of the actor’s mailbox.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 81 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(akka_actor_mailbox_size_sum{job=\"hk-tcgateway\"}[5m])>0) by (dispatcher)",
     "legendFormat": "{{dispatcher}}"
    }
   ]
  },
  {
   "title": "TCHK - Redis PUB/SUB",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_publisher_datakeys_publish_bucket{job=\"hk-tcgateway\"}[5m])>0)",
     "legendFormat": "Redis_Pub"
    },
    {
     "expr": "sum(irate(redis_subscriber_datakeys_received_bucket{job=\"hk-tcgateway\"}[5m])>0)",
     "legendFormat": "Redis_Sub"
    }
   ]
  },
  {
   "title": "TCHK Gateway Processing Time",
   "type": "graph",
   "description": "TCHK Gateway Processing Time from metric *akka.actor.processing-time (Histogram): Tracks how long did it take for the actor to process every message",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(akka_actor_processing_time_seconds_bucket{group=\"tchk\",job=\"hk-tcgateway\"}[5m])>0)",
     "legendFormat": "Gateway Processing time "
    },
    {}
   ]
  },
  {
   "title": "Proxy Request total",
   "type": "graph",
   "description": "This graph represent the number of PubRequests, SubRequests, from Spreadsheets on TCHK proxy1,2",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(central_incoming_requests_total{type=\"client-pub-request\",group=\"tchk\"}[5m])>0",
     "legendFormat": "{{type}}{{job}}"
    },
    {
     "expr": "irate(central_incoming_requests_total{type=\"client-sub-request\",group=\"tchk\"}[5m])>0",
     "legendFormat": "{{type}}{{job}}"
    }
   ]
  },
  { "title": "Procession time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 112 } },
  {
   "title": "GW processing_time Histogram_Quantile",
   "type": "graph",
   "description": "akka.actor.processing-time (Histogram): Tracks how long did it take for the actor to process every message.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(akka_actor_processing_time_seconds_bucket{job=\"hk-tcgateway\"}[5m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "G/W router_ processing_time Histogram_Quantile",
   "type": "graph",
   "description": "akka.router.processing-time (Histogram): Tracks how long did it take for the routees to process incoming messages. This histogram includes measurements from all routees.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 126 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(akka_router_processing_time_seconds_bucket{job=\"hk-tcgateway\"}[5m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Reactor processing_time Histogram_Quantile",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 139 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(akka_actor_processing_time_seconds_bucket{job=\"hk-treactor\"}[5m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "GW*DEMO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 152 },
   "collapsed": true,
   "panels": [
    {
     "title": "Gateway Mailbox",
     "type": "graph",
     "description": "*akka.actor.time-in-mailbox (Histogram): Tracks the time measured from the moment a message was enqueued into an actor’s mailbox until the moment it was dequeued for processing.\n*akka.actor.processing-time (Histogram): Tracks how long did it take for the actor to process every message.\n*akka.actor.mailbox-size (Range Sampler): Tracks the size of the actor’s mailbox.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 153 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(akka_actor_mailbox_size_sum{job=\"hk-tcgateway\"}[5m])>0) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Panel Title",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 153 },
     "targets": [
      {
       "expr": "akka_group_processing_time_seconds_sum"
      }
     ]
    },
    {
     "title": "TCHK Gateway Processing Time",
     "type": "graph",
     "description": "TCHK Gateway Processing Time from metric *akka.actor.processing-time (Histogram): Tracks how long did it take for the actor to process every message",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 164 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "akka_router_time_in_mailbox_seconds_bucket"
      }
     ]
    },
    {
     "title": "TCHK Gateway historgram",
     "type": "graph",
     "description": "TCHK Gateway Processing Time from metric *akka.actor.processing-time (Histogram): Tracks how long did it take for the actor to process every message",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 164 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(gateway_datakeys_updated_bucket{group=\"tchk\"}[10m])) by (le)"
      }
     ]
    },
    {
     "title": "TCHK Gateway historgram",
     "type": "graph",
     "description": "TCHK Gateway Processing Time from metric *akka.actor.processing-time (Histogram): Tracks how long did it take for the actor to process every message",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 173 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(increase(gateway_datakeys_updated_bucket{group=\"tchk\"}[10m])) by (le)"
      }
     ]
    }
   ]
  },
  {
   "title": "TCP*Demo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCHK  Json over TCP",
     "type": "graph",
     "description": "legacy-session  json over TCP incoming_requests_sum",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(legacy_session_incoming_requests_sum{group=\"tchk\",type=\"client-pub-request\"}[5m])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "TCHK  Json over TCP",
     "type": "graph",
     "description": "legacy-session  json over TCP incoming_requests_sum",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(legacy_session_incoming_requests_sum{group=\"tchk\",type=\"client-pub-request\"}[5m])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "TCHK  Json over TCP unhandled_total",
     "type": "graph",
     "description": "legacy-session  json over TCP (legacy_session_unhandled_total",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(legacy_session_unhandled_total{group=\"tchk\"}[5m])",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "TCHK  Json over TCP",
     "type": "graph",
     "description": "legacy-session  json over TCP incoming_requests_sum",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(legacy_session_incoming_requests_sum{group=\"tchk\",type=\"client-pub-request\"}[5m])",
       "legendFormat": "{{job}}"
      }
     ]
    }
   ]
  }
 ]
}