{
 "title": "TCJP-MD team",
 "description": "Created by Lenny.cm",
 "tags": [
  "Prometheus",
  "TCJP",
  "alerts"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Gateway Interface status",
   "type": "table",
   "gridPos": { "h": 5, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "gateway_interface_status{group=\"tctk\"}"
    }
   ]
  },
  { "title": "Services Notification", "type": "alertlist", "gridPos": { "h": 5, "w": 10, "x": 14, "y": 0 } },
  { "title": "TCJP by Lenny", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "TCJP8 - Proxy connection",
   "type": "singlestat",
   "description": "spreadsheets connections on Proxy",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "central_current_sessions{job=\"tk-tcproxy-tctk8\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "TCJP10 - Proxy connection",
   "type": "singlestat",
   "description": "spreadsheets connections on Proxy",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "central_current_sessions{job=\"tk-tcproxy-tctk10\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "TCJP9 - Proxy connection",
   "type": "singlestat",
   "description": "spreadsheets connections on Proxy",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "central_current_sessions{job=\"tk-tcproxy-tctk9\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "TCJP - Gateway Processing",
   "type": "graph",
   "description": "akka_actor_processing_time_seconds_bucket",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(akka_actor_processing_time_seconds_sum{job=\"tk-tcgateway\"}[5m])>0)",
     "legendFormat": "TK-tcgateway"
    },
    {}
   ]
  },
  {
   "title": "Tracer State TC Gateway",
   "type": "singlestat",
   "description": "round trip time\n0 = off, 1 = ok, 2 = error",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "tracer_state{job=\"tk-tcgateway\"}"
    }
   ]
  },
  {
   "title": "Tracer State TC gissingpub",
   "type": "singlestat",
   "description": "round trip time\n0 = off, 1 = ok, 2 = error",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "tracer_state{instance=\"172.30.2.109:9092\"}"
    }
   ]
  },
  {
   "title": "TCJP - Gateway Subscribers",
   "type": "singlestat",
   "description": "The number of subscribers (e.g. Proxy, Feed, GissingSub...) currently connected.\n      * This corresponds to the number of RMQ queues we are sending data to",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "admin_subscribers{job=\"tk-tcgateway\"}"
    }
   ]
  },
  {
   "title": "TCJP - G/W No permission Subscriber",
   "type": "singlestat",
   "description": "The number of subscription requests that were rejected because the requester did not have permission to read the SourceRecord",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "admin_user_no_permission_total{job=\"tk-tcgateway\"}"
    }
   ]
  },
  {
   "title": "TCJP - Proxy",
   "type": "graph",
   "description": "Proxy Processing  time",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "velocityms" }
   ],
   "targets": [
    {
     "expr": "rate(gateway_interface_gateway_data_updates_total{job=\"tk-tcproxy-tctk3\"}[5m])>0",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "rate(gateway_interface_gateway_data_updates_total{job=\"tk-tcproxy-tctk2\"}[5m])>0",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "rate(gateway_interface_gateway_data_updates_total{job=\"tk-tcproxy-tctk4\"}[5m])>0",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "rate(gateway_interface_gateway_data_updates_total{job=\"tk-tcproxy-tctk5\"}[5m])>0",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "rate(gateway_interface_gateway_data_updates_total{job=\"tk-tcproxy-tctk8\"}[5m])>0",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "rate(gateway_interface_gateway_data_updates_total{job=\"tk-tcproxy-tctk10\"}[5m])>0",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "rate(gateway_interface_gateway_data_updates_total{job=\"tk-tcproxy-tctk9\"}[5m])>0",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "TCJP - Reactor",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(akka_system_processed_messages_total{tracked=\"true\",job=\"tk-treactor\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "TCJP - Proxy Connection",
   "type": "graph",
   "description": "The count of heartbeats received from any service",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "central_current_sessions{group=\"tctk\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "TCJP - Gissingpub ,sub",
   "type": "graph",
   "description": "This is the number of data updates we are passing to the throttle directly from Gissing\n(pre-throttle-accepted)",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(gissing_publish_duration_seconds_count{job=\"tk-tcgissingpub\"}[5m])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "increase(pre_throttle_accepted_total{job=\"tk-tcgissingsub\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "TCJP - Replicator",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "akka_system_active_actors_count{job=\"tk-tcreplicatorSG\"}",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "akka_system_active_actors_count{job=\"tk-tcreplicatorHK\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Gateway Mail box",
   "type": "graph",
   "description": "Tracks the time measured from the moment a message was enqueued into an actor’s mailbox until the moment it was dequeued for processing.\n\n*akka.actor.mailbox-size : Tracks the size of the actor’s mailbox.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(akka_group_time_in_mailbox_seconds_sum{job=\"hk-tcgateway\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "TCJP - History",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(akka_system_processed_messages_total{tracked=\"true\",job=\"tk-tchistory\"}[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "TCJP - Reactor",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(akka_actor_processing_time_seconds_bucket{job=\"tk-treactor\"}[5m]))",
     "legendFormat": "tk-treactor"
    }
   ]
  },
  {
   "title": "TCJP - Redis DKs Publishers/Subscribers",
   "type": "graph",
   "description": "The number of datakeys saved to the Redis key-value store. The same keys are also published to Redis Channels for other services (like Reactor) to pick up.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(redis_publisher_datakeys_publish_bucket{job=\"tk-tcgateway\"}[5m]))",
     "legendFormat": "Redis-Publisher"
    },
    {
     "expr": "sum(irate(redis_subscriber_datakeys_received_bucket{job=\"tk-tcgateway\"}[5m]))",
     "legendFormat": "Redis-Subscriber"
    }
   ]
  },
  {
   "title": "TCJP - RPC Services",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "akka_system_processed_messages_total{job=\"tk-tcrpcserver\"}",
     "legendFormat": "{{job}}+{{tracked}}"
    },
    {}
   ]
  },
  {
   "title": "Processing histogram quantile",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true
  },
  {
   "title": "G/W actor processing_time_seconds histogram_quantile",
   "type": "graph",
   "description": "akka.router.processing-time (Histogram): Tracks how long did it take for the routees to process incoming messages. This histogram includes measurements from all routees.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(akka_actor_processing_time_seconds_bucket{job=\"tk-tcgateway\"}[5m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "G/W akka.router.processing-time histogram_quantile",
   "type": "graph",
   "description": "Tracks how long did it take for the routees to process incoming messages. This histogram includes measurements from all routees.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 82 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(akka_router_processing_time_seconds_bucket{job=\"hk-tcgateway\"}[5m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Reactor processing_time_seconds histogram_quantile",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(akka_actor_processing_time_seconds_bucket{job=\"tk-treactor\"}[5m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "DEMO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 108 },
   "collapsed": true,
   "panels": [
    {
     "title": "TCJP - History * TEST",
     "type": "table",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 109 },
     "targets": [
      {
       "expr": "gateway_service_heartbeat_received_total_total"
      }
     ]
    },
    {
     "title": "TCJP - History-File Writer * TEST",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 109 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(akka_actor_processing_time_seconds_count{job=\"tk-tchistory\",dispatcher=\"akka.actor.default-dispatcher\"}[5m])>0",
       "legendFormat": "{{path}}"
      },
      {}
     ]
    },
    {
     "title": "REDIS* TEST",
     "type": "graph",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 118 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(redis_publisher_datakeys_publish_sum{job=\"tk-tcgateway\"}[5m])"
      }
     ]
    }
   ]
  }
 ]
}